// hospitalNames.ts

/**
 * A list of general hospital names in Ontario, Canada.
 * Data sourced from ontario.ca, updated as of August 18, 2025.
 * This list has been alphabetized and deduplicated.
 */
const hospitalNamesList: string[] = [
    "Ajax and Pickering Health Centre (Ajax)",
    "Alexandra Hospital",
    "Alexandra Marine And General Hospital",
    "Almonte General Hospital",
    "Anson General Hospital",
    "Arnprior And District Memorial Hospital (The)",
    "Atikokan Health and Community Services",
    "Attawapiskat Hospital",
    "Baycrest Hospital",
    "Bayshore Drive Site (Midland)",
    "Belleville General Hospital",
    "Bingham Memorial Hospital",
    "Blanche River Health - Englehart Site",
    "Blanche River Health - Kirkland Lake Site",
    "Bluewater Health - Sarnia Site",
    "Bowmanville Hospital",
    "Brampton Civic Hospital",
    "Breast Imaging Kingston Centre",
    "Brockville Dialysis Clinic",
    "Brockville General Hospital",
    "Brockville Mental Health Centre",
    "Cambridge Memorial Hospital",
    "Campbellford Memorial Hospital",
    "Carleton Place And District Memorial Hospital",
    "Casey House",
    "Centre for Addiction and Mental Health - College Street Site",
    "Centre for Addiction and Mental Health - Queen Street Site",
    "Charlotte Eleanor Englehart Hospital (Petrolia)",
    "Chatham - Kent Health Alliance - Chatham Site",
    "Chatham - Kent Health Alliance - Wallaceburg Site",
    "Children's Hospital",
    "Children's Hospital Of Eastern Ontario-Ottawa Children's Treatment Centre",
    "Clinton Public Hospital",
    "Collingwood General And Marine Hospital",
    "Cornwall Community Hospital/Hôpital communautaire de Cornwall",
    "Cornwall Dialysis Clinic",
    "Cortellucci Vaughan Hospital (Vaughan)",
    "Credit Valley Hospital",
    "Deep River And District Health",
    "Douglas Memorial Site (Fort Erie)",
    "Dryden Regional Health Centre",
    "Emo Health Centre",
    "Erie Shores HealthCare",
    "Espanola General Hospital",
    "Etobicoke General Hospital (Toronto)",
    "Fort Albany Hospital",
    "Four Counties Health Services Corporation",
    "Georgetown Hospital",
    "Georgian Bay General Hospital - Main Site",
    "Georgian Bay General Hospital - Prospect Boulevard Site",
    "Geraldton District Hospital",
    "Glengarry Memorial Hospital",
    "Greater Niagara General Hospital (Niagara Falls)",
    "Groves Memorial Community Hospital",
    "Guelph General Hospital",
    "Haliburton Site",
    "Haldimand War Memorial Hospital",
    "Hamilton General Hospital",
    "Hanover And District Hospital",
    "Hawkesbury And District General Hospital",
    "Headwaters Health Care Centre",
    "Health Sciences North - Children's Treatment Centre",
    "Health Sciences North - Kirkwood Site",
    "Health Sciences North - Ramsey Lake Health Centre",
    "Hennick Bridgepoint Hospital",
    "Holland Bloorview Kids Rehabilitation Hospital",
    "Hornepayne Community Hospital",
    "Hospital For Sick Children (The)",
    "Hôtel-Dieu Grace Healthcare - Tayfour Campus",
    "Hôtel-Dieu Shaver Health and Rehabilitation Centre",
    "Hotel Dieu Hospital",
    "Hôpital Montfort",
    "Hôpital Notre-Dame Hospital (Hearst)",
    "Humber River Hospital",
    "Huntsville District Memorial Hospital",
    "Irving Greenberg Family Cancer Centre",
    "Jane Street Site (Vaughan)",
    "Jerry Coughlan Health and Wellness Centre (Pickering)",
    "Joseph Brant Hospital",
    "Juravinski Hospital and Cancer Centre",
    "Kemptville District Hospital",
    "Kingston General Hospital",
    "La Verendrye Hospital",
    "Lady Dunn Health Centre",
    "Lady Minto Hospital (The)",
    "Lake-Of-The-Woods District Hospital",
    "Lennox And Addington County General Hospital",
    "Lion's Head Hospital",
    "Listowel Memorial Hospital",
    "Louise Marshall Hospital",
    "Mackenzie Richmond Hill Hospital",
    "Manitoulin Health Centre - Little Current Hospital",
    "Manitoulin Health Centre - Mindemoya Hospital",
    "Marianhill - Complex Continuing Care Site",
    "Markdale Hospital",
    "Markham-Stouffville Hospital",
    "Marotta Family Hospital",
    "Mattawa General Hospital",
    "McCausland Hospital (Terrace Bay)",
    "McMaster Children's Hospital",
    "McMaster University Medical Centre",
    "Meaford Hospital",
    "Milton District Hospital",
    "Minden Site",
    "Mississauga Hospital",
    "Moosonee Health Centre",
    "Mount Sinai Hospital",
    "Niagara Health System - Welland Site",
    "Nipigon District Memorial Hospital",
    "Norfolk General Hospital",
    "North Bay Regional Health Centre - Devonshire Avenue Site",
    "North Bay Regional Health Centre - King Street Site",
    "North Bay Regional Health Centre - Kirkwood Place Site",
    "North Bay Regional Health Centre - North Bay Site",
    "North Hastings Hospital (Bancroft)",
    "North Shore Health Network - Blind River Site",
    "North Shore Health Network - Richards Landing Site",
    "North Shore Health Network - Thessalon Site",
    "North York General Hospital - Finch Site",
    "North York General Hospital - General Site",
    "Northumberland Hills Hospital",
    "NYGH Minor Surgical Procedures & Elder Care Centre",
    "NYGH Outpatient & Community Services Centre",
    "Oakville Trafalgar Memorial Hospital",
    "Ontario Shores Centre for Mental Health Sciences",
    "Orillia Soldiers' Memorial Hospital",
    "Orleans Health Hub (OHH) /Carrefour Santé Orleans (CSO)",
    "Oshawa Hospital",
    "Ottawa Dialysis Clinic",
    "Owen Sound Regional Hospital",
    "Palmerston and District Hospital",
    "Parkwood Institute",
    "Peel Memorial Centre for Integrated Health and Wellness",
    "Pembroke Regional Hospital Site",
    "Perth And Smiths Falls District Hospital - Great War Memorial Site (Perth)",
    "Perth And Smiths Falls District Hospital - Smith Falls Site",
    "Peterborough Regional Health Centre",
    "Phillips House",
    "Port Colborne Site",
    "Port Perry Hospital",
    "Prince Edward County Memorial Hospital (Picton)",
    "Princess Margaret Cancer Centre",
    "Providence Care Hospital",
    "Providence Healthcare",
    "Queensway Health Centre (Toronto)",
    "Queensway-Carleton Hospital",
    "Rainy River Health Centre",
    "Reactivation Care Centre - Church (Toronto)",
    "Reactivation Care Centre - Finch (Toronto)",
    "Reactivation Care Centre- Church",
    "Red Lake Margaret Cochenour Memorial Hospital (The)",
    "Renfrew Victoria Hospital",
    "Ross Memorial Hospital",
    "Royal Ottawa Mental Health Centre",
    "Royal Victoria Regional Health Centre",
    "Runnymede Healthcare Centre",
    "Saint-Vincent Hospital",
    "Salvation Army Toronto Grace Health Centre (The)",
    "Santé Manitouwadge Health",
    "Sault Area Hospital",
    "Saugeen Shores Hospital",
    "Scarborough Health Network - Birchmount Site",
    "Scarborough Health Network - Centenary Site",
    "Scarborough Health Network - General Site",
    "Seaforth Community Hospital",
    "Sensenbrenner Hospital (The)",
    "Services De Sante De Chapleau Health Services",
    "Sioux Lookout Meno-Ya-Win Health Centre",
    "Smooth Rock Falls Hospital",
    "South Bruce Grey Health Centre - Chesley Site",
    "South Bruce Grey Health Centre - Durham Site",
    "South Bruce Grey Health Centre - Kincardine Site",
    "South Bruce Grey Health Centre - Walkerton Site",
    "South Huron Hospital",
    "South Muskoka Memorial Hospital (Bracebridge)",
    "Southlake Regional Health Centre - Newmarket Site",
    "Southwest Centre for Forensic Mental Health Care (St. Thomas)",
    "Speakman Dialysis Care Centre",
    "St Francis Memorial Hospital",
    "St Thomas-Elgin General Hospital",
    "St. Joseph's Continuing Care Centre",
    "St. Joseph's Continuing Care Centre of Sudbury - Lasalle site",
    "St. Joseph's Continuing Care Centre of Sudbury - South Bay Road site",
    "St. Joseph's General Hospital",
    "St. Joseph's Health Centre",
    "St. Joseph's Health Centre Guelph",
    "St. Joseph's Healthcare Hamilton - Charlton Campus",
    "St. Joseph's Healthcare Hamilton - King Campus",
    "St. Joseph's Healthcare Hamilton - Stedman House (Brantford)",
    "St. Joseph's Healthcare Hamilton - West 5th Campus",
    "St. Joseph's Hospital (London)",
    "St. Joseph's Hospital (Thunder Bay)",
    "St. Mary's Memorial Hospital",
    "St. Michael's Hospital",
    "St. Peter's Hospital",
    "Stevenson Memorial Hospital",
    "Stratford General Hospital",
    "Strathroy Middlesex General Hospital",
    "Street Health Centre",
    "Sunnybrook Health Sciences Centre - Bayview Campus",
    "Sunnybrook Health Sciences Centre - Holland Centre",
    "Sunnybrook Health Sciences Centre - St. John's Rehab",
    "Temiskaming Hospital",
    "The Brantford General Hospital",
    "The Ottawa Hospital - Civic Campus",
    "The Ottawa Hospital - General Campus",
    "The Ottawa Hospital - Riverside Campus",
    "The Rehabilitation Centre",
    "The Willett Hospital (Paris)",
    "Thunder Bay Regional Health Sciences Centre",
    "Tillsonburg District Memorial Hospital",
    "Timmins And District General Hospital",
    "Toronto East Health Network - Michael Garron Hospital",
    "Toronto General Hospital",
    "Toronto Western Hospital",
    "Transitional Care Centre",
    "Trenton Memorial Hospital (Trenton)",
    "UHN Reactivation Care Centre (Toronto)",
    "University Health Network - Bickle Centre",
    "University Health Network - Hillcrest Site",
    "University Health Network - Lyndhurst Centre",
    "University Health Network - Rumsey Centre",
    "University Health Network - University Centre",
    "University Hospital",
    "University of Ottawa Heart Institute",
    "Uxbridge Hospital",
    "Victoria Hospital",
    "Waterloo Regional Health Network - Chicopee",
    "Waterloo Regional Health Network - Midtown",
    "Waterloo Regional Health Network - Queen's Boulevard",
    "Waypoint Centre for Mental Health Care (main site)",
    "Weeneebayko General Hospital",
    "West End Clinic",
    "West Haldimand General Hospital",
    "West Lincoln Memorial Hospital (Grimsby)",
    "West Nipissing General Hospital",
    "West Park Healthcare Centre",
    "West Parry Sound Health Centre",
    "Whitby Hospital",
    "Wiarton Hospital",
    "Wilson Memorial General Hospital",
    "Winchester District Memorial Hospital",
    "Windsor Regional Hospital - Maryvale Campus",
    "Windsor Regional Hospital - Metropolitan Campus",
    "Windsor Regional Hospital - Ouellete Campus",
    "Wingham And District Hospital",
    "Women's College Hospital",
    "Woodstock Hospital",
    "Élisabeth Bruyère Hospital",
  ];

  const toSlug = (str: string) => str.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-');

  export const ontarioHospitals = hospitalNamesList.map(name => ({
      label: name,
      value: toSlug(name)
  }));
  ontarioHospitals.push({ label: "Other", value: "other" });
  
  export default hospitalNamesList;
