export const provinces = [
  { label: 'Alberta', value: 'AB' },
  { label: 'British Columbia', value: 'BC' },
  { label: 'Manitoba', value: 'MB' },
  { label: 'New Brunswick', value: 'NB' },
  { label: 'Newfoundland and Labrador', value: 'NL' },
  { label: 'Nova Scotia', value: 'NS' },
  { label: 'Ontario', value: 'ON' },
  { label: 'Prince Edward Island', value: 'PE' },
  { label: 'Quebec', value: 'QC' },
  { label: 'Saskatchewan', value: 'SK' },
  { label: 'Northwest Territories', value: 'NT' },
  { label: 'Nunavut', value: 'NU' },
  { label: 'Yukon', value: 'YT' },
];

export const ontarioCities = [
    { label: "Other", value: "other" },
    { label: "Toronto", value: "toronto" },
    { label: "Ottawa", value: "ottawa" },
    { label: "Mississauga", value: "mississauga" },
    { label: "Brampton", value: "brampton" },
    { label: "Hamilton", value: "hamilton" },
    { label: "London", value: "london" },
    { label: "Markham", value: "markham" },
    { label: "Vaughan", value: "vaughan" },
    { label: "Kitchener", value: "kitchener" },
    { label: "Windsor", value: "windsor" },
    { label: "Richmond Hill", value: "richmond-hill" },
    { label: "Oakville", value: "oakville" },
    { label: "Burlington", value: "burlington" },
    { label: "Greater Sudbury", value: "greater-sudbury" },
    { label: "Oshawa", value: "oshawa" },
    { label: "Barrie", value: "barrie" },
    { label: "Guelph", value: "guelph" },
    { label: "Cambridge", value: "cambridge" },
    { label: "St. Catharines", value: "st-catharines" },
    { label: "Kingston", value: "kingston" },
    { label: "Thunder Bay", value: "thunder-bay" },
    { label: "Waterloo", value: "waterloo" },
    { label: "Ajax", value: "ajax" },
    { label: "Pickering", value: "pickering" },
    { label: "Niagara Falls", value: "niagara-falls" },
    
];
