export const provinces = [
  { label: 'Alberta', value: 'AB' },
  { label: 'British Columbia', value: 'BC' },
  { label: 'Manitoba', value: 'MB' },
  { label: 'New Brunswick', value: 'NB' },
  { label: 'Newfoundland and Labrador', value: 'NL' },
  { label: 'Nova Scotia', value: 'NS' },
  { label: 'Ontario', value: 'ON' },
  { label: 'Prince Edward Island', value: 'PE' },
  { label: 'Quebec', value: 'QC' },
  { label: 'Saskatchewan', value: 'SK' },
  { label: 'Northwest Territories', value: 'NT' },
  { label: 'Nunavut', value: 'NU' },
  { label: 'Yukon', value: 'YT' },
];

/** Ontario cities for forms and region mapping. "Other" is reserved for free-text entries. */
export const ontarioCities = [
  { label: 'Other', value: 'other' },
  // GTA & Golden Horseshoe
  { label: 'Toronto', value: 'toronto' },
  { label: 'Mississauga', value: 'mississauga' },
  { label: 'Brampton', value: 'brampton' },
  { label: 'Markham', value: 'markham' },
  { label: 'Vaughan', value: 'vaughan' },
  { label: 'Richmond Hill', value: 'richmond-hill' },
  { label: 'Oakville', value: 'oakville' },
  { label: 'Burlington', value: 'burlington' },
  { label: 'Oshawa', value: 'oshawa' },
  { label: 'Barrie', value: 'barrie' },
  { label: 'Ajax', value: 'ajax' },
  { label: 'Pickering', value: 'pickering' },
  { label: 'Newmarket', value: 'newmarket' },
  { label: 'Whitby', value: 'whitby' },
  { label: 'Milton', value: 'milton' },
  { label: 'Georgina', value: 'georgina' },
  { label: 'Aurora', value: 'aurora' },
  { label: 'King City', value: 'king-city' },
  { label: 'Bradford West Gwillimbury', value: 'bradford-west-gwillimbury' },
  // Hamilton-Wentworth
  { label: 'Hamilton', value: 'hamilton' },
  { label: 'Stoney Creek', value: 'stoney-creek' },
  { label: 'Ancaster', value: 'ancaster' },
  { label: 'Dundas', value: 'dundas' },
  { label: 'Flamborough', value: 'flamborough' },
  // East
  { label: 'Ottawa', value: 'ottawa' },
  { label: 'Kingston', value: 'kingston' },
  { label: 'Cornwall', value: 'cornwall' },
  { label: 'Belleville', value: 'belleville' },
  { label: 'Peterborough', value: 'peterborough' },
  { label: 'Brockville', value: 'brockville' },
  { label: 'Pembroke', value: 'pembroke' },
  { label: 'Clarence-Rockland', value: 'clarence-rockland' },
  { label: 'Quinte West', value: 'quinte-west' },
  { label: 'Prince Edward County', value: 'prince-edward-county' },
  { label: 'Smiths Falls', value: 'smiths-falls' },
  { label: 'Prescott', value: 'prescott' },
  { label: 'Gananoque', value: 'gananoque' },
  { label: 'Carleton Place', value: 'carleton-place' },
  { label: 'Arnprior', value: 'arnprior' },
  { label: 'Renfrew', value: 'renfrew' },
  // Niagara / East
  { label: 'St. Catharines', value: 'st-catharines' },
  { label: 'Niagara Falls', value: 'niagara-falls' },
  { label: 'Welland', value: 'welland' },
  { label: 'Port Colborne', value: 'port-colborne' },
  { label: 'Thorold', value: 'thorold' },
  { label: 'Fort Erie', value: 'fort-erie' },
  { label: 'Lincoln', value: 'lincoln' },
  { label: 'Grimsby', value: 'grimsby' },
  // West
  { label: 'London', value: 'london' },
  { label: 'Windsor', value: 'windsor' },
  { label: 'Kitchener', value: 'kitchener' },
  { label: 'Waterloo', value: 'waterloo' },
  { label: 'Cambridge', value: 'cambridge' },
  { label: 'Guelph', value: 'guelph' },
  { label: 'Sarnia', value: 'sarnia' },
  { label: 'Chatham-Kent', value: 'chatham-kent' },
  { label: 'St. Thomas', value: 'st-thomas' },
  { label: 'Woodstock', value: 'woodstock' },
  { label: 'Brantford', value: 'brantford' },
  { label: 'Brant', value: 'brant' },
  { label: 'Stratford', value: 'stratford' },
  { label: 'Norfolk County', value: 'norfolk-county' },
  { label: 'Haldimand County', value: 'haldimand-county' },
  { label: 'Kawartha Lakes', value: 'kawartha-lakes' },
  { label: 'Owen Sound', value: 'owen-sound' },
  { label: 'Leamington', value: 'leamington' },
  { label: 'Essex', value: 'essex' },
  { label: 'Amherstburg', value: 'amherstburg' },
  { label: 'Tecumseh', value: 'tecumseh' },
  { label: 'Lambton Shores', value: 'lambton-shores' },
  { label: 'Tillsonburg', value: 'tillsonburg' },
  { label: 'St. Marys', value: 'st-marys' },
  // North
  { label: 'Greater Sudbury', value: 'greater-sudbury' },
  { label: 'Thunder Bay', value: 'thunder-bay' },
  { label: 'North Bay', value: 'north-bay' },
  { label: 'Sault Ste. Marie', value: 'sault-ste-marie' },
  { label: 'Timmins', value: 'timmins' },
  { label: 'Kenora', value: 'kenora' },
  { label: 'Elliot Lake', value: 'elliot-lake' },
  { label: 'Dryden', value: 'dryden' },
  { label: 'Temiskaming Shores', value: 'temiskaming-shores' },
  { label: 'Orillia', value: 'orillia' },
  { label: 'Sudbury', value: 'sudbury' },
  { label: 'Kapuskasing', value: 'kapuskasing' },
  { label: 'Cochrane', value: 'cochrane' },
  { label: 'Hearst', value: 'hearst' },
  { label: 'Sioux Lookout', value: 'sioux-lookout' },
  { label: 'Parry Sound', value: 'parry-sound' },
  { label: 'Temagami', value: 'temagami' },
];
